import {
  Layers,
  IdCard,
  Trophy,
  Flag,
  Briefcase,
  MapPin,
  Store,
  ShoppingBag,
  Megaphone,
  ShieldCheck,
  Users,
  Newspaper,
  ClipboardList,
  Settings,
  Menu,
  X,
  LogOut,
  Calendar,
  Award,
  UserPlus,
  SlidersHorizontal,
  ListOrdered,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  RotateCcw,
  Maximize,
  BarChart3,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  Layers,
  IdCard,
  Trophy,
  Flag,
  Briefcase,
  MapPin,
  Store,
  ShoppingBag,
  Megaphone,
  ShieldCheck,
  Users,
  Newspaper,
  ClipboardList,
  Settings,
  Menu,
  X,
  LogOut,
  Calendar,
  Award,
  UserPlus,
  SlidersHorizontal,
  ListOrdered,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  RotateCcw,
  Maximize,
  BarChart3,
};

/** Icono generico por nombre (nav y categorias de noticia comparten este mapa unico). */
export function Icon({ name, className = "h-4 w-4" }: { name: string; className?: string }) {
  const IconComponent = ICONS[name] ?? Megaphone;
  return <IconComponent className={className} aria-hidden="true" />;
}
